### ISSUE TITLE
Use vcpkg for dependency resolution by default

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/emf2svg-ruby#23]
### Intro / Proposed solution

 - https://github.com/metanorma/emf2svg-ruby/issues/21#issuecomment-1086739617

### Open questions

 - [ ] Should we force the user to install `vcpkg` if it missing?
       - @CAMOBAP IMHO we should use it only if it is presented and in case of an error ask a user to install it

**Comment by maxirmx** [comment]
We now have vcpkg bootstrap code included into libemf2svg as submodule so that it creates a virtual environment.   It is transparent for the user.

The tricky point is different.  vcpkg is not a silver bullet.  libemf2svg depends on argp and memstreams that are linux features not natively provided anywhere else and not supported by vcpkg.  Furthermore, argp is a part of glibc, memstreams are very-low-level and both are not really maintined as standalone portable packages.

So we discussing vcpkg on *nix/mac platforms just to install libpng while most of the complexity of libemf2svg ports will be resolved outside.

vcpkg apllies differently to cross-compilation because of virtial environment mentioned above. In case of cross-compilation we need full environment for target platform on top of which we can build or install argp, memstreams and libemf2svg

**Comment by maxirmx** [comment]
The bottom line is that I can change the build configuration for this gem so that vcpkg is always used for dependency resolution, but I'm very skeptical of any improvements in simplification or future portability.
If these are the objectives then libemf2svg refactoring is needed first

**Comment by maxirmx** [comment]
he previous decision was "don't spend a lot of time and money on this library". If it has changed, it will take me 1-2 weeks to resolve portability issues in a more general way.
@ronaldtse ?

**Comment by ronaldtse** [comment]
@maxirmx we will need to make packed-mn work on Alpine, so if improvements to libemf2svg is necessary, we should make it happen. Or can we just rely on the `gcompat` libc compatibility package on Alpine for packed-mn?
